export const fishImages = {
    'asagi.jpg': require('../assets/images/asagi.jpg'),
    'kohaku.jpg': require('../assets/images/kohaku.jpg'),
    'showa.jpg': require('../assets/images/showa.jpg'),
    'shiro.jpg': require('../assets/images/shiro.jpg'),
    'kujaku.jpg': require('../assets/images/kujaku.jpg'),
  };
  
  export const koiData = [
    {
      id: 1,
      name: 'Asagi',
      variant: 'Jin',
      description: 'Cá Koi Asagi là một trong những giống cá Koi cổ xưa và mang tính biểu tượng nhất, được đánh giá cao về màu sắc hài hòa và thanh lịch.',
      imageName: 'asagi.jpg',
      likes: 21,
      liked: false,
      size: 2,
    },
    {
      id: 2,
      name: 'Kohaku',
      variant: 'Tancho',
      description: 'Kohaku được coi là vua của các loài Koi, với thân hình trắng và các hoa văn đỏ. Biến thể Tancho có một đốm đỏ duy nhất trên đầu.',
      imageName: 'kohaku.jpg',
      likes: 18,
      liked: false,
      size: 2,
    },
    {
      id: 3,
      name: 'Showa',
      variant: 'Sanshoku',
      description: 'Showa Sanshoku là cá Koi ba màu với nền đen, điểm xuyết các hoa văn đỏ và trắng, tạo nên vẻ ngoài đậm nét và ấn tượng.',
      imageName: 'showa.jpg',
      likes: 15,
      liked: false,
      size: 2,
    },
    {
      id: 4,
      name: 'Shiro Utsuri',
      variant: 'Platinum',
      description: 'Shiro Utsuri là cá Koi hai màu với nền trắng và các đốm đen. Nổi tiếng với sự tương phản ấn tượng và kiểu bơi thanh lịch.',
      imageName: 'shiro.jpg',
      likes: 25,
      liked: false,
      size: 2,
    },
    {
      id: 5,
      name: 'Kujaku',
      variant: 'Metallic',
      description: 'Kujaku là giống Koi ánh kim với nền trắng cùng các hoa văn cam, đỏ và đen chảy dọc thân, giống như bộ lông của chim công.',
      imageName: 'kujaku.jpg',
      likes: 19,
      liked: false,
      size: 2,
    },
  ];